---
- hosts: dev
  become: yes
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: install docker
      yum:
        name: docker
        state: present
    - name: start the docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: start the container
      docker_container:
        name: myappnow2021
        image: "pnkr5454/mycicd:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:9090:8080  
    - name: discard the docker images 
      command: docker image prune -a -f --filter 'label=app=my-app' 
      ignore_errors: yes  

